/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.donorpkg;

import business.common.DOBValidation;
import business.common.EmailValidation;
import business.common.ZipValidation;
import business.common.PhoneNumberValidation;
import business.common.InputValidation;
import business.person.Person;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author riaka
 */
public class CreateDonorProfileJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    
    /**
     * Creates new form CreateDonorProfile
     */
    public CreateDonorProfileJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        addInputVerifiers();
        donorNameField.setText(userAccount.getPerson().getFullName());
        donorName.setVisible(true);
    }
    
    
    private void addInputVerifiers() {
          
        InputVerifier stringValidation = new InputValidation();
        donorNameField.setInputVerifier(stringValidation);
        addressField.setInputVerifier(stringValidation);
        townField.setInputVerifier(stringValidation);
        occupationField.setInputVerifier(stringValidation);
        
        InputVerifier dobValidtion = new DOBValidation();
        donorDobField.setInputVerifier(dobValidtion);
        
        InputVerifier numberValidation = new ZipValidation();
        zipCodeField.setInputVerifier(numberValidation);
        
        InputVerifier phnumberValidation = new PhoneNumberValidation();
        phoneNumberField.setInputVerifier(phnumberValidation);
         
            InputVerifier emailValidtion = new EmailValidation();
            emailIDField.setInputVerifier(emailValidtion);
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateOfBirth = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        town = new javax.swing.JLabel();
        townField = new javax.swing.JTextField();
        zipCode = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        createYourProfile = new javax.swing.JLabel();
        donorName = new javax.swing.JLabel();
        donorNameField = new javax.swing.JTextField();
        zipCodeField = new javax.swing.JTextField();
        occupation = new javax.swing.JLabel();
        occupationField = new javax.swing.JTextField();
        emailID = new javax.swing.JLabel();
        emailIDField = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        createProfileButton = new javax.swing.JButton();
        donorDobField = new javax.swing.JFormattedTextField();
        manageEnt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(169, 224, 49));

        dateOfBirth.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dateOfBirth.setForeground(new java.awt.Color(169, 224, 49));
        dateOfBirth.setText("Date Of Birth (MM/DD/YYYY)");

        address.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(169, 224, 49));
        address.setText("Address");

        addressField.setBackground(new java.awt.Color(0, 0, 0));
        addressField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        addressField.setForeground(new java.awt.Color(169, 224, 49));
        addressField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        town.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        town.setForeground(new java.awt.Color(169, 224, 49));
        town.setText("Town/City");

        townField.setBackground(new java.awt.Color(0, 0, 0));
        townField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        townField.setForeground(new java.awt.Color(169, 224, 49));
        townField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        zipCode.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        zipCode.setForeground(new java.awt.Color(169, 224, 49));
        zipCode.setText("Zip Code");

        backJButton.setBackground(new java.awt.Color(169, 224, 49));
        backJButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        createYourProfile.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        createYourProfile.setForeground(new java.awt.Color(169, 224, 49));
        createYourProfile.setText("Create Donor Profile");

        donorName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        donorName.setForeground(new java.awt.Color(169, 224, 49));
        donorName.setText("Full Name");

        donorNameField.setEditable(false);
        donorNameField.setBackground(new java.awt.Color(0, 0, 0));
        donorNameField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        donorNameField.setForeground(new java.awt.Color(169, 224, 49));
        donorNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        donorNameField.setEnabled(false);

        zipCodeField.setBackground(new java.awt.Color(0, 0, 0));
        zipCodeField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        zipCodeField.setForeground(new java.awt.Color(169, 224, 49));
        zipCodeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        occupation.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        occupation.setForeground(new java.awt.Color(169, 224, 49));
        occupation.setText("Occupation");

        occupationField.setBackground(new java.awt.Color(0, 0, 0));
        occupationField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        occupationField.setForeground(new java.awt.Color(169, 224, 49));
        occupationField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        emailID.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        emailID.setForeground(new java.awt.Color(169, 224, 49));
        emailID.setText("Email Address");

        emailIDField.setBackground(new java.awt.Color(0, 0, 0));
        emailIDField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        emailIDField.setForeground(new java.awt.Color(169, 224, 49));
        emailIDField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        phoneNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        phoneNumber.setForeground(new java.awt.Color(169, 224, 49));
        phoneNumber.setText("Phone Number");

        phoneNumberField.setBackground(new java.awt.Color(0, 0, 0));
        phoneNumberField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        phoneNumberField.setForeground(new java.awt.Color(169, 224, 49));
        phoneNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        createProfileButton.setBackground(new java.awt.Color(169, 224, 49));
        createProfileButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        createProfileButton.setText("Create Profile ");
        createProfileButton.setBorder(null);
        createProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfileButtonActionPerformed(evt);
            }
        });

        donorDobField.setBackground(new java.awt.Color(0, 0, 0));
        donorDobField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        donorDobField.setForeground(new java.awt.Color(169, 224, 49));
        donorDobField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        manageEnt.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        manageEnt.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt.setText("Donation Department Portal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateOfBirth, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(donorName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(town, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(occupation, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zipCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(phoneNumberField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(donorDobField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(zipCodeField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(townField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(occupationField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailIDField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addressField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(donorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createYourProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(manageEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(manageEnt)
                .addGap(36, 36, 36)
                .addComponent(createYourProfile)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donorName)
                        .addGap(18, 18, 18)
                        .addComponent(dateOfBirth)
                        .addGap(18, 18, 18)
                        .addComponent(address)
                        .addGap(18, 18, 18)
                        .addComponent(town)
                        .addGap(18, 18, 18)
                        .addComponent(occupation)
                        .addGap(18, 18, 18)
                        .addComponent(emailID)
                        .addGap(21, 21, 21)
                        .addComponent(zipCode)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(donorDobField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(townField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(occupationField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(createProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void createProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileButtonActionPerformed
        Person person = userAccount.getPerson();
        
        if( addressField.getText().trim().isEmpty() ||
             townField.getText().trim().isEmpty() ||
            occupationField.getText().trim().isEmpty() ||
             emailIDField.getText().trim().isEmpty() ||
           phoneNumberField.getText().trim().isEmpty() || 
             donorDobField.getText().trim().isEmpty() ||
            zipCodeField.getText().trim().isEmpty() ) 
        {
        JOptionPane.showMessageDialog(null, "Please Enter data in all the fields");
           return;        
        }
        
        try
        {
          DateFormat dateFormat =  new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date();
        Date dob =  dateFormat.parse(donorDobField.getText());
        if(dob.after(date) || dob.equals(date))
        {
         JOptionPane.showMessageDialog(null, "Please Enter valid Date of Birth");
           return;    
        }
            person.setDateOfBirth(dateFormat.parse(donorDobField.getText()));
            person.setAddress1(addressField.getText());
            person.setTown(townField.getText());
            person.setOccupation(occupationField.getText());
            person.setZipCode(zipCodeField.getText());
            person.setEmailId(emailIDField.getText());
            person.setMobileNumber(phoneNumberField.getText());      
            
            JOptionPane.showMessageDialog(null, "Your Profile has been created successfully", "success", JOptionPane.PLAIN_MESSAGE);
            resetFields();       
        }
        catch(ParseException pe)
        {
           JOptionPane.showMessageDialog(null, "Please Enter valid date of Birth!");
           return;   
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, "Please Enter valid data in all the fields");
           return;     
        }
    }//GEN-LAST:event_createProfileButtonActionPerformed

public void resetFields()
{
    donorNameField.setText("");
    donorDobField.setText("");
    addressField.setText("");
    townField.setText("");
    occupationField.setText("");
    zipCodeField.setText("");
    emailIDField.setText("");
    phoneNumberField.setText("");
    
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createProfileButton;
    private javax.swing.JLabel createYourProfile;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JFormattedTextField donorDobField;
    private javax.swing.JLabel donorName;
    private javax.swing.JTextField donorNameField;
    private javax.swing.JLabel emailID;
    private javax.swing.JTextField emailIDField;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JLabel occupation;
    private javax.swing.JTextField occupationField;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JLabel town;
    private javax.swing.JTextField townField;
    private javax.swing.JLabel zipCode;
    private javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
