/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.donorpkg;

import business.EcoSystem;
import business.common.Donation;
import business.common.ZipValidation;
import business.common.PhoneNumberValidation;
import business.common.InputValidation;
import business.common.Validation;
import business.organizations.SupervisorOrganization;
import business.userAccount.UserAccount;
import business.workQueue.DonationRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author riaka
 */
public class DonationJPanelWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
   
    /**
     * Creates new form DonationJPanelWorkArea
     */
    public DonationJPanelWorkArea(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        addInputVerifiers();
        toAccntNumberField.setText(Donation.NGOAccountNumber);
    }
    

    
      private void addInputVerifiers() {
        InputVerifier noValidation = new ZipValidation();
        amountField.setInputVerifier(noValidation);
        monthField.setInputVerifier(noValidation);
        yearField.setInputVerifier(noValidation);
        
        InputVerifier phnumberValidation = new PhoneNumberValidation();
        cardNumberField.setInputVerifier(phnumberValidation);
        
         
        InputVerifier stringValidation = new InputValidation();
        nameTxtField.setInputVerifier(stringValidation);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnt = new javax.swing.JLabel();
        helpName = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        expiryDate = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        toAccntNumber = new javax.swing.JLabel();
        toAccntNumberField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(169, 224, 49));

        manageEnt.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        manageEnt.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt.setText("Donate Money");

        helpName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        helpName.setForeground(new java.awt.Color(169, 224, 49));
        helpName.setText("Enter Card Number (10 Digits)");

        cardNumberField.setBackground(new java.awt.Color(0, 0, 0));
        cardNumberField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cardNumberField.setForeground(new java.awt.Color(169, 224, 49));
        cardNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        expiryDate.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        expiryDate.setForeground(new java.awt.Color(169, 224, 49));
        expiryDate.setText("Enter Expiry Date(MM/YYYY)");

        monthField.setBackground(new java.awt.Color(0, 0, 0));
        monthField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        monthField.setForeground(new java.awt.Color(169, 224, 49));
        monthField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        yearField.setBackground(new java.awt.Color(0, 0, 0));
        yearField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        yearField.setForeground(new java.awt.Color(169, 224, 49));
        yearField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        amount.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        amount.setForeground(new java.awt.Color(169, 224, 49));
        amount.setText("Enter Amount");

        amountField.setBackground(new java.awt.Color(0, 0, 0));
        amountField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        amountField.setForeground(new java.awt.Color(169, 224, 49));
        amountField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        submitBtn.setBackground(new java.awt.Color(169, 224, 49));
        submitBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.setBorder(null);
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(169, 224, 49));
        cancelBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(null);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(169, 224, 49));
        name.setText("Enter Name");

        nameTxtField.setBackground(new java.awt.Color(0, 0, 0));
        nameTxtField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        nameTxtField.setForeground(new java.awt.Color(169, 224, 49));
        nameTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        toAccntNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        toAccntNumber.setForeground(new java.awt.Color(169, 224, 49));
        toAccntNumber.setText("NGO Account Number");

        toAccntNumberField.setEditable(false);
        toAccntNumberField.setBackground(new java.awt.Color(0, 0, 0));
        toAccntNumberField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        toAccntNumberField.setForeground(new java.awt.Color(169, 224, 49));
        toAccntNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        toAccntNumberField.setEnabled(false);

        backJButton.setBackground(new java.awt.Color(169, 224, 49));
        backJButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 367, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(helpName)
                        .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amount)
                            .addComponent(expiryDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameTxtField)
                                .addComponent(amountField)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(312, 312, 312))
            .addGroup(layout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(manageEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toAccntNumber)
                .addGap(18, 18, 18)
                .addComponent(toAccntNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(manageEnt)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toAccntNumber)
                    .addComponent(toAccntNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpName)
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDate)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
       if(nameTxtField.getText().trim().isEmpty() || 
               cardNumberField.getText().length()>10 || 
               monthField.getText().length()>2 || 
               yearField.getText().length()>4 || amountField.getText().length()<0)
       {
        JOptionPane.showMessageDialog(null, "Please enter valid input!", "warning",JOptionPane.WARNING_MESSAGE);
        return;       
       }
       try
       {
       int month = Integer.parseInt(monthField.getText());
       int year = Integer.parseInt(yearField.getText());
       if(month<0 || month > 12)
       {
       JOptionPane.showMessageDialog(null, "Please enter month between 1 and 12!", "warning",JOptionPane.WARNING_MESSAGE);
        return;     
       }
       if(year<2015 || year>2050)
       {
        JOptionPane.showMessageDialog(null, "Please enter valid expiry year!", "warning",JOptionPane.WARNING_MESSAGE);
        return;       
       }
      
       DateFormat df = new SimpleDateFormat("EEE, MMM d, YYYY hh:mm aaa");
       Calendar cal = Calendar.getInstance();
       String timestamp = df.format(cal.getTime());
       
       Donation donation = userAccount.getPerson().addDonation();
       
       donation.setDonationAmount(amountField.getText());
       donation.setDateOfDonation(timestamp);
       donation.setDonorAccName(nameTxtField.getText());
       donation.setDonorAccNumber(cardNumberField.getText());
      
           try
           {
           DonationRequest donationRequest = new DonationRequest();
           donationRequest.setDonationAmount(donation);
           donationRequest.setNameOfDonor(userAccount.getuName());
           donationRequest.setSender(userAccount);
           donationRequest.setRequestDate(new Date());
           donationRequest.setMessage("Donated Money");
           
           userAccount.getWorkQueue().getWorkRequestList().add(donationRequest);
           
           UserAccount ua = getSeniorSafeManagerAccnt();
           if(ua==null)
           {
            JOptionPane.showMessageDialog(null, "Please verify if senior safe manager acccount exists!", "warning",JOptionPane.WARNING_MESSAGE);
           userAccount.getWorkQueue().getWorkRequestList().remove(donationRequest);  
            return;   
           }
           if(ua!=null)
           {
            donationRequest.setReceiver(ua);
            donationRequest.setResolveDate(new Date());
            ua.getWorkQueue().getWorkRequestList().add(donationRequest); 
            donationRequest.setStatus("Completed");
           JOptionPane.showMessageDialog(null, "Donation has been made successfully, Thank You", "success",JOptionPane.PLAIN_MESSAGE);
            }
           else
           {
           userAccount.getWorkQueue().getWorkRequestList().remove(donationRequest);  
           }
           }
           catch(Exception e)
            {
           JOptionPane.showMessageDialog(null, "Please verify if senior safe manager acccount exists!", "warning",JOptionPane.WARNING_MESSAGE);
           return;      
            }
        resetFields();
      }
       catch(Exception e)
       {
      JOptionPane.showMessageDialog(null, "Please enter valid data!", "warning",JOptionPane.WARNING_MESSAGE);
       return;      
       }
    }//GEN-LAST:event_submitBtnActionPerformed
    
    public UserAccount getSeniorSafeManagerAccnt()
    {
        try
        {
        SupervisorOrganization supervisorOrganization = (SupervisorOrganization)Validation.getSOrg(ecoSystem, userAccount);
        UserAccount mngrAccnt = null;
        if(supervisorOrganization==null)
        {
        JOptionPane.showMessageDialog(null, "Supervisor Organization does not exist!", "warning",JOptionPane.WARNING_MESSAGE);
        return mngrAccnt;  
        }
      
        for(UserAccount ua : supervisorOrganization.getUserAccountDirectory().getUserAccountDirectory())
        {
            
         if((ua.getRole().toString()).equals("SeniorSafeManagerRole"))  
         {
          mngrAccnt = ua;   
         }
        }
        return mngrAccnt;
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, "Please verify if Supervisor organization exist!", "warning",JOptionPane.WARNING_MESSAGE);
        
        return null;      
        }
   
    }
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
       resetFields();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    public void resetFields()
    {
     cardNumberField.setText("");
     monthField.setText("");
     yearField.setText("");
     amountField.setText("");
     nameTxtField.setText("");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JLabel expiryDate;
    private javax.swing.JLabel helpName;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JTextField monthField;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel toAccntNumber;
    private javax.swing.JTextField toAccntNumberField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
