/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.serviceSeeker;

import business.EcoSystem;
import business.common.NeedService;
import business.organizations.VolunteerOrganization;
import business.person.Volunteer;
import business.userAccount.UserAccount;
import business.workQueue.NeedServiceRequest;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prasanna
 */
public class RequestVolunteerForHelp extends javax.swing.JPanel {
    
    private Volunteer volunteer;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private VolunteerOrganization organization;
    private EcoSystem ecoSystem;
    
    public RequestVolunteerForHelp(JPanel userProcessContainer, UserAccount userAccount, Volunteer volunteer, VolunteerOrganization organization,EcoSystem ecoSystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.volunteer = volunteer;
        this.organization = (VolunteerOrganization)organization;
        this.ecoSystem = ecoSystem;
        
        populateNeedHelpListTable();
        otherHelpPanel.setVisible(false);
        
        populateVolunteerDetails();
       
        populateHelpHistoryTable();
        
    }
    
   
    
    public void populateHelpHistoryTable()
    {
     DefaultTableModel dtm = (DefaultTableModel)workRequestHistoryTable.getModel();
        dtm.setRowCount(0);
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy"); 
     for(WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList())
        {
         if(workRequest.getMessage().equalsIgnoreCase("Need Help"))
         {
           Object[] rowData = new Object[5];
           rowData[0] = ((NeedServiceRequest)workRequest).getRequestId();
           rowData[1] = ((NeedServiceRequest)workRequest).getNeedHelp().getService();
           rowData[2] = dateFormat.format(workRequest.getRequestDate());
           rowData[3] = workRequest.getReceiver() == null ? null : workRequest.getReceiver().getuName() ;
           rowData[4] = workRequest.getStatus();
           
           dtm.addRow(rowData);
         }
        }       
    }
    
    public void populateVolunteerDetails()
    {
        DateFormat dateFormat = new SimpleDateFormat("MM/DD/YYYY");
                
        firstNameField.setText(volunteer.getPersonsFirstName());
        lastNameField.setText(volunteer.getlName());
        dobField.setText(dateFormat.format(volunteer.getDateOfBirth()));
        genderField.setText(volunteer.getGender());
    }
    
    public void populateNeedHelpListTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)helpjTable.getModel();
        dtm.setRowCount(0);
        
        for(NeedService nh : ecoSystem.getServiceList() )
        {

           Object[] rowData = new Object[4];
           rowData[0] = nh;
           rowData[1] = nh.getService();
           rowData[2] = nh.getServiceDesc();
           rowData[3] = nh.getNewService()== null ? null : nh.getNewService() ;
           dtm.addRow(rowData);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnt2 = new javax.swing.JLabel();
        manageEnt1 = new javax.swing.JLabel();
        manageEnt3 = new javax.swing.JLabel();
        manageEnt4 = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        dobField = new javax.swing.JFormattedTextField();
        firstName = new javax.swing.JLabel();
        viewYourProfile = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JLabel();
        genderField = new javax.swing.JTextField();
        otherHelpPanel = new javax.swing.JPanel();
        helpDetails = new javax.swing.JLabel();
        serviceTypeCombo = new javax.swing.JComboBox();
        helpDetailsTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        serviceType = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestHistoryTable = new javax.swing.JTable();
        manageEnt5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        helpjTable = new javax.swing.JTable();
        newHelpRadioBtn = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnCreateRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 36, 42));

        manageEnt2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        manageEnt2.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageEnt2.setText("Senior Safe");

        manageEnt1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        manageEnt1.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt1.setText("Required service not in the Table");

        manageEnt3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        manageEnt3.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt3.setText("Service Request History");

        manageEnt4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        manageEnt4.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt4.setText("Select the radio button  ");

        LastName.setForeground(new java.awt.Color(169, 224, 49));
        LastName.setText("Last Name:");

        firstNameField.setEditable(false);
        firstNameField.setBackground(new java.awt.Color(32, 36, 42));
        firstNameField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        firstNameField.setEnabled(false);

        gender.setForeground(new java.awt.Color(169, 224, 49));
        gender.setText("Gender:");

        dobField.setBackground(new java.awt.Color(32, 36, 42));
        dobField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        dobField.setForeground(new java.awt.Color(255, 255, 255));
        dobField.setEnabled(false);

        firstName.setForeground(new java.awt.Color(169, 224, 49));
        firstName.setText("First Name:");

        viewYourProfile.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        viewYourProfile.setForeground(new java.awt.Color(169, 224, 49));
        viewYourProfile.setText("Volunteer Details:");

        lastNameField.setEditable(false);
        lastNameField.setBackground(new java.awt.Color(32, 36, 42));
        lastNameField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        lastNameField.setEnabled(false);

        dateOfBirth.setForeground(new java.awt.Color(169, 224, 49));
        dateOfBirth.setText("Date Of Birth ");

        genderField.setBackground(new java.awt.Color(32, 36, 42));
        genderField.setForeground(new java.awt.Color(255, 255, 255));
        genderField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        genderField.setEnabled(false);

        otherHelpPanel.setBackground(new java.awt.Color(31, 36, 42));

        helpDetails.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        helpDetails.setForeground(new java.awt.Color(169, 224, 49));
        helpDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        helpDetails.setText(" Enter details about the service needed.");

        serviceTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select Amount", "5$", "10$", "15$", "20$" }));

        helpDetailsTxtField.setBackground(new java.awt.Color(32, 36, 42));
        helpDetailsTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setText("Enter details of service needed: ");

        serviceType.setForeground(new java.awt.Color(169, 224, 49));
        serviceType.setText("Service Type");

        javax.swing.GroupLayout otherHelpPanelLayout = new javax.swing.GroupLayout(otherHelpPanel);
        otherHelpPanel.setLayout(otherHelpPanelLayout);
        otherHelpPanelLayout.setHorizontalGroup(
            otherHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherHelpPanelLayout.createSequentialGroup()
                .addGroup(otherHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpDetails)
                    .addGroup(otherHelpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(otherHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(serviceType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(otherHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serviceTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(helpDetailsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otherHelpPanelLayout.setVerticalGroup(
            otherHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherHelpPanelLayout.createSequentialGroup()
                .addComponent(helpDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(otherHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(helpDetailsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(otherHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceType))
                .addGap(57, 57, 57))
        );

        workRequestHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Service Recieved", "Requested Date", "Volunteer ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestHistoryTable);

        manageEnt5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        manageEnt5.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt5.setText("Request Volunteer For Service");

        helpjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Service Needed", "Service Type", "Service Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(helpjTable);

        newHelpRadioBtn.setBackground(new java.awt.Color(31, 36, 42));
        newHelpRadioBtn.setForeground(new java.awt.Color(169, 224, 49));
        newHelpRadioBtn.setText("New service");
        newHelpRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newHelpRadioBtnActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(152, 201, 45));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(21, 25, 28));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreateRequest.setBackground(new java.awt.Color(152, 201, 45));
        btnCreateRequest.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCreateRequest.setForeground(new java.awt.Color(21, 25, 28));
        btnCreateRequest.setText("Create Request");
        btnCreateRequest.setBorder(null);
        btnCreateRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateRequest.setFocusPainted(false);
        btnCreateRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageEnt5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(389, 389, 389)
                                .addComponent(manageEnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215)
                                .addComponent(btnCreateRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(otherHelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageEnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewYourProfile)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateOfBirth)
                                            .addComponent(LastName))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(gender)
                                            .addGap(12, 12, 12)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(genderField)
                                        .addComponent(lastNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dobField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(manageEnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manageEnt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newHelpRadioBtn)
                        .addGap(496, 496, 496)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(manageEnt2)
                .addGap(19, 19, 19)
                .addComponent(manageEnt5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewYourProfile)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstName)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastName)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfBirth)
                            .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageEnt1)
                    .addComponent(manageEnt4)
                    .addComponent(newHelpRadioBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(manageEnt3)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(otherHelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newHelpRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newHelpRadioBtnActionPerformed
        populateComboBxHelpType();
        otherHelpPanel.setVisible(true);
    }//GEN-LAST:event_newHelpRadioBtnActionPerformed

    private void btnCreateRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRequestActionPerformed
        // TODO add your handling code here:
    
        NeedService needService;
      
        if(newHelpRadioBtn.isSelected())
        {
            
        if(helpDetailsTxtField.getText().trim().isEmpty() || serviceTypeCombo.getSelectedIndex() <0)
        {
       JOptionPane.showMessageDialog(this, "Please Enter data in all the fields ", "warning", JOptionPane.PLAIN_MESSAGE);
         return;      
        }
        needService = ecoSystem.addNeedService();
        needService.setService("Others");
        needService.setNewService(helpDetailsTxtField.getText());
        needService.setServiceDesc((String)serviceTypeCombo.getSelectedItem());
       }
         else
         {
        int selectedRow = helpjTable.getSelectedRow();
        if(selectedRow<0)
        {
        JOptionPane.showMessageDialog(this, "Please select a row", "warning", JOptionPane.PLAIN_MESSAGE);
         return;    
        }
        
        needService = (NeedService)helpjTable.getValueAt(selectedRow, 0);
         
    
            
//        String message = "hello";
//        
//        NeedServiceRequest needHelpWorkRequest = new NeedServiceRequest();
//        needHelpWorkRequest.setMessage("Need Help");
//        needHelpWorkRequest.setSender(userAccount);
//        needHelpWorkRequest.setStatus("Sent");
//        needHelpWorkRequest.setNeedHelp(needService);
//        needHelpWorkRequest.setHelpDetails(message);
//        needHelpWorkRequest.setRequestDate(new Date());
//        
//        UserAccount volunteerAccount = null;
//        if (organization!=null){
//            for(UserAccount ua: organization.getUserAccountDirectory().getUserAccountDirectory())
//            {
//                 if(ua.getPerson().getPersonIdentificationNo().equals(volunteer.getPersonIdentificationNo()))
//                 {
//                 volunteerAccount=ua;    
//                 }
//                
//            }
//            volunteerAccount.getWorkQueue().getWorkRequestList().add(needHelpWorkRequest);
//            userAccount.getWorkQueue().getWorkRequestList().add(needHelpWorkRequest);
//        }
//         JOptionPane.showMessageDialog(null, "Request has been created successfully", "success", JOptionPane.PLAIN_MESSAGE);
//        
           
        }
       
        SubmitServiceRequestJPanel submitHelpRequestJPanel = new SubmitServiceRequestJPanel(userProcessContainer, userAccount,volunteer, needService, organization);
        userProcessContainer.add("SubmitHelpRequestJPanel", submitHelpRequestJPanel);
        newHelpRadioBtn.setSelected(false);
        helpDetailsTxtField.setText("");
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnCreateRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    
    public void populateComboBxHelpType()
    {
      serviceTypeCombo.removeAllItems();
      serviceTypeCombo.addItem("Immediate");
      serviceTypeCombo.addItem("Need in a day");
      serviceTypeCombo.addItem("Not Immediate service");
      serviceTypeCombo.addItem("In a Week");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateRequest;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JFormattedTextField dobField;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel helpDetails;
    private javax.swing.JTextField helpDetailsTxtField;
    private javax.swing.JTable helpjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel manageEnt2;
    private javax.swing.JLabel manageEnt3;
    private javax.swing.JLabel manageEnt4;
    private javax.swing.JLabel manageEnt5;
    private javax.swing.JRadioButton newHelpRadioBtn;
    private javax.swing.JPanel otherHelpPanel;
    private javax.swing.JLabel serviceType;
    private javax.swing.JComboBox serviceTypeCombo;
    private javax.swing.JLabel viewYourProfile;
    private javax.swing.JTable workRequestHistoryTable;
    // End of variables declaration//GEN-END:variables
}
