/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.serviceSeeker;

import business.EcoSystem;
import business.common.Validation;
import business.network.Network;
import business.organizations.VolunteerOrganization;
import business.person.Volunteer;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.openstreetmap.gui.jmapviewer.Coordinate;
import org.openstreetmap.gui.jmapviewer.JMapViewer;
import org.openstreetmap.gui.jmapviewer.MapMarkerDot;
import org.openstreetmap.gui.jmapviewer.MapPolygonImpl;
import org.openstreetmap.gui.jmapviewer.Style;
import org.openstreetmap.gui.jmapviewer.events.JMVCommandEvent;
import org.openstreetmap.gui.jmapviewer.interfaces.ICoordinate;
import org.openstreetmap.gui.jmapviewer.interfaces.JMapViewerEventListener;
import userInterface.volunteer.ViewVolunteerProfile;

/**
 *
 * @author prasanna
 */
public class SearchForVolunteerJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount; 
    private EcoSystem ecoSystem;
    private VolunteerOrganization volOrg;
    

   
    /**
     * Creates new form SearchForVolunteerJPanel
     */
    public SearchForVolunteerJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
       
        populateNetworkComboBox();
        //setBackground(new Color(182,201,233));
         
       
       
    }
    

    public void populateNetworkComboBox()
    {
        networkListComboBox.removeAllItems();
        for(Network network: ecoSystem.getNetworkList())
        {
           networkListComboBox.addItem(network);
        }
    }

    

    
    public void populateVolunteerListTable(Network network)
    {
       
        DefaultTableModel model = (DefaultTableModel)volunteerListTable.getModel();
        model.setRowCount(0); 
        try
        {
        volOrg = (VolunteerOrganization)Validation.getVoInNetwork(ecoSystem, network);
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(this, "Volunteer Organization has not been created yet!", "warning",JOptionPane.WARNING_MESSAGE);
          return;   
        }
        if(volOrg.getPersonDirectory().getVolunteerDirectory().isEmpty())
        {
        JOptionPane.showMessageDialog(this, "No Volunteers to display as of now", "warning",JOptionPane.WARNING_MESSAGE);
          return;    
        }

     for(UserAccount volunteerAccnt : volOrg.getUserAccountDirectory().getUserAccountDirectory())
       {
        if(volunteerAccnt.isEnabled())
        {
        Volunteer volunteer = (Volunteer)volunteerAccnt.getPerson();    
        if(volunteerAccnt.getNetwork().getCity().equals(network.getCity()))
        {
           Object[] row = new Object[5];
            row[0] = volunteer.getVolunteerId();
            row[1] = volunteer;
            row[2] = volunteer.getGender();
            row[3] = volunteer.getTown();
            row[4] = volunteerAccnt;
            model.addRow(row);   
        }
        }
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkListComboBox = new javax.swing.JComboBox();
        manageEnt1 = new javax.swing.JLabel();
        manageEnt2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        volunteerListTable = new javax.swing.JTable();
        btnViewVolunteersProfile = new javax.swing.JButton();
        btnRequestVolunteerForHelp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 36, 42));

        networkListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkListComboBoxActionPerformed(evt);
            }
        });

        manageEnt1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        manageEnt1.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt1.setText("Search For Volunteer");

        manageEnt2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        manageEnt2.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt2.setText("Senior Safe");

        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setText("Network:");

        volunteerListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Volunteer Id", "Name", "Gender", "City", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(volunteerListTable);
        if (volunteerListTable.getColumnModel().getColumnCount() > 0) {
            volunteerListTable.getColumnModel().getColumn(0).setResizable(false);
            volunteerListTable.getColumnModel().getColumn(1).setResizable(false);
            volunteerListTable.getColumnModel().getColumn(2).setResizable(false);
            volunteerListTable.getColumnModel().getColumn(3).setResizable(false);
            volunteerListTable.getColumnModel().getColumn(4).setResizable(false);
        }

        btnViewVolunteersProfile.setBackground(new java.awt.Color(152, 201, 45));
        btnViewVolunteersProfile.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        btnViewVolunteersProfile.setForeground(new java.awt.Color(21, 25, 28));
        btnViewVolunteersProfile.setText("View Volunteer Profile");
        btnViewVolunteersProfile.setBorder(null);
        btnViewVolunteersProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewVolunteersProfile.setFocusPainted(false);
        btnViewVolunteersProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVolunteersProfileActionPerformed(evt);
            }
        });

        btnRequestVolunteerForHelp.setBackground(new java.awt.Color(152, 201, 45));
        btnRequestVolunteerForHelp.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        btnRequestVolunteerForHelp.setForeground(new java.awt.Color(21, 25, 28));
        btnRequestVolunteerForHelp.setText("Request Volunteer For Service");
        btnRequestVolunteerForHelp.setBorder(null);
        btnRequestVolunteerForHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRequestVolunteerForHelp.setFocusPainted(false);
        btnRequestVolunteerForHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestVolunteerForHelpActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(152, 201, 45));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(21, 25, 28));
        btnBack.setText("back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(manageEnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(networkListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(manageEnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRequestVolunteerForHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnViewVolunteersProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(733, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(manageEnt2)
                .addGap(18, 18, 18)
                .addComponent(manageEnt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestVolunteerForHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewVolunteersProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkListComboBoxActionPerformed
       if(networkListComboBox.getSelectedIndex()>=0)
       {
            Network network = (Network)networkListComboBox.getSelectedItem();
       
         populateVolunteerListTable(network); 
         //populateMApToViewVolunteers();
       }
      
    }//GEN-LAST:event_networkListComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestVolunteerForHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestVolunteerForHelpActionPerformed
        // TODO add your handling code here:
                int selectedRow = volunteerListTable.getSelectedRow();
        if(selectedRow<0)
        {
         JOptionPane.showMessageDialog(this, "Please select a volunteer", "warning", JOptionPane.PLAIN_MESSAGE);
         return;   
        }
        
        Volunteer volunteer = (Volunteer)volunteerListTable.getValueAt(selectedRow, 1);
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestVolunteerForHelp", new RequestVolunteerForHelp(userProcessContainer, userAccount, volunteer, volOrg, ecoSystem));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnRequestVolunteerForHelpActionPerformed

    private void btnViewVolunteersProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVolunteersProfileActionPerformed
        // TODO add your handling code here:
         int selectedRow = volunteerListTable.getSelectedRow();
        if(selectedRow<0)
        {
         JOptionPane.showMessageDialog(this, "Please select a volunteer", "warning", JOptionPane.PLAIN_MESSAGE);
         return;   
        }
        
        UserAccount volUserAccount = (UserAccount)volunteerListTable.getValueAt(selectedRow, 4);
        
        
         ViewVolunteerProfile viewVolunteerProfile = new ViewVolunteerProfile(userProcessContainer, volUserAccount);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         userProcessContainer.add("ViewVolunteerProfile", viewVolunteerProfile);
         layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewVolunteersProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestVolunteerForHelp;
    private javax.swing.JButton btnViewVolunteersProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel manageEnt2;
    private javax.swing.JComboBox networkListComboBox;
    private javax.swing.JTable volunteerListTable;
    // End of variables declaration//GEN-END:variables


}
