/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.serviceSeeker;

import business.common.NeedService;
import business.organizations.VolunteerOrganization;
import business.person.Volunteer;
import business.userAccount.UserAccount;
import business.workQueue.NeedServiceRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prasanna
 */
public class SubmitServiceRequestJPanel extends javax.swing.JPanel {

    
     private NeedService needService;
     private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Volunteer volunteer;
    private VolunteerOrganization organization;
    
    /**
     * Creates new form SubmitHelpRequestJPanel
     */
    public SubmitServiceRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, Volunteer volunteer, NeedService needService, VolunteerOrganization organization) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.volunteer = volunteer;
        this.organization = organization;
        this.needService = needService;
       
         populateVolunteerDetails();
         populateNeedHelpReqTable();
    }
    

    
     public void populateVolunteerDetails()
    {
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                
        firstNameField.setText(volunteer.getPersonsFirstName());
        lastNameField.setText(volunteer.getlName());
        dobField.setText(dateFormat.format(volunteer.getDateOfBirth()));
        genderField.setText(volunteer.getGender());
    }
     
     public void populateNeedHelpReqTable()
     {
         helpNameTxtField.setText(needService.getService());
         serviceTypeTxtField.setText(needService.getServiceDesc());
        
     }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnt3 = new javax.swing.JLabel();
        submitRequest = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        genderField = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        viewYourProfile = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        dobField = new javax.swing.JFormattedTextField();
        gender = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        LastName1 = new javax.swing.JLabel();
        commentsTextField = new javax.swing.JTextField();
        serviceTypeTxtField = new javax.swing.JTextField();
        viewYourProfile1 = new javax.swing.JLabel();
        firstName1 = new javax.swing.JLabel();
        gender1 = new javax.swing.JLabel();
        helpNameTxtField = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        manageEnt3.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt3.setText("Request Volunteer For Help:");

        setBackground(new java.awt.Color(31, 36, 42));

        submitRequest.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        submitRequest.setForeground(new java.awt.Color(169, 224, 49));
        submitRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitRequest.setText("Submit Request to Volunteer For Service");

        LastName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        LastName.setForeground(new java.awt.Color(169, 224, 49));
        LastName.setText("Last Name:");

        genderField.setBackground(new java.awt.Color(31, 36, 42));
        genderField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        genderField.setEnabled(false);

        dateOfBirth.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dateOfBirth.setForeground(new java.awt.Color(169, 224, 49));
        dateOfBirth.setText("Date Of Birth ");

        lastNameField.setEditable(false);
        lastNameField.setBackground(new java.awt.Color(31, 36, 42));
        lastNameField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        lastNameField.setEnabled(false);

        viewYourProfile.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        viewYourProfile.setForeground(new java.awt.Color(169, 224, 49));
        viewYourProfile.setText("Volunteer Details:");

        firstName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        firstName.setForeground(new java.awt.Color(169, 224, 49));
        firstName.setText("First Name:");

        dobField.setBackground(new java.awt.Color(31, 36, 42));
        dobField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        dobField.setEnabled(false);

        gender.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gender.setForeground(new java.awt.Color(169, 224, 49));
        gender.setText("Gender:");

        firstNameField.setEditable(false);
        firstNameField.setBackground(new java.awt.Color(31, 36, 42));
        firstNameField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        firstNameField.setEnabled(false);

        LastName1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        LastName1.setForeground(new java.awt.Color(169, 224, 49));
        LastName1.setText("Service Type:");

        commentsTextField.setBackground(new java.awt.Color(31, 36, 42));
        commentsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        serviceTypeTxtField.setEditable(false);
        serviceTypeTxtField.setBackground(new java.awt.Color(31, 36, 42));
        serviceTypeTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        serviceTypeTxtField.setEnabled(false);

        viewYourProfile1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        viewYourProfile1.setForeground(new java.awt.Color(169, 224, 49));
        viewYourProfile1.setText("Service Request Details:");

        firstName1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        firstName1.setForeground(new java.awt.Color(169, 224, 49));
        firstName1.setText("Need Service:");

        gender1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gender1.setForeground(new java.awt.Color(169, 224, 49));
        gender1.setText("Comments:");

        helpNameTxtField.setEditable(false);
        helpNameTxtField.setBackground(new java.awt.Color(31, 36, 42));
        helpNameTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        helpNameTxtField.setEnabled(false);

        btnSubmit.setBackground(new java.awt.Color(152, 201, 45));
        btnSubmit.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(21, 25, 28));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(null);
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setFocusPainted(false);
        btnSubmit.setMaximumSize(new java.awt.Dimension(52, 21));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(152, 201, 45));
        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(21, 25, 28));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(152, 201, 45));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(21, 25, 28));
        btnBack.setText("back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewYourProfile)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dateOfBirth)
                                                    .addComponent(LastName))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(gender)
                                                    .addGap(12, 12, 12)))
                                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(genderField)
                                            .addComponent(lastNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dobField)
                                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(70, 70, 70)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewYourProfile1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastName1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(serviceTypeTxtField)
                                    .addComponent(helpNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(gender1)
                                .addGap(60, 60, 60)
                                .addComponent(commentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(244, Short.MAX_VALUE))
            .addComponent(submitRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(submitRequest)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewYourProfile1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstName1)
                            .addComponent(helpNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(serviceTypeTxtField)
                                .addGap(1, 1, 1))
                            .addComponent(LastName1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender1))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewYourProfile)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstName)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastName)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfBirth)
                            .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

                if(commentsTextField.getText().trim().isEmpty())
        {
         JOptionPane.showMessageDialog(null, "Please Enter comments.", "warning",JOptionPane.WARNING_MESSAGE);
         return;
        }
        try
        {
            
        String message = commentsTextField.getText();
        
        NeedServiceRequest needHelpWorkRequest = new NeedServiceRequest();
        needHelpWorkRequest.setMessage("Need Help");
        needHelpWorkRequest.setSender(userAccount);
        needHelpWorkRequest.setStatus("Sent");
        needHelpWorkRequest.setNeedHelp(needService);
        needHelpWorkRequest.setHelpDetails(message);
        needHelpWorkRequest.setRequestDate(new Date());
        
        UserAccount volunteerAccount = null;
        if (organization!=null){
            for(UserAccount ua: organization.getUserAccountDirectory().getUserAccountDirectory())
            {
                 if(ua.getPerson().getPersonIdentificationNo().equals(volunteer.getPersonIdentificationNo()))
                 {
                 volunteerAccount=ua;    
                 }
                
            }
            volunteerAccount.getWorkQueue().getWorkRequestList().add(needHelpWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(needHelpWorkRequest);
        }
         JOptionPane.showMessageDialog(null, "Request has been created successfully", "success", JOptionPane.PLAIN_MESSAGE);
         commentsTextField.setText("");
           
        }
         catch(NullPointerException e)
        {
         JOptionPane.showMessageDialog(null, "Unable to send request, Please try again !!", "warning", JOptionPane.WARNING_MESSAGE);
         return;
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null, "Unable to send request, Please try again !!", "warning", JOptionPane.WARNING_MESSAGE);
         return;
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
            userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RequestVolunteerForHelp requestVolunteerForHelp = (RequestVolunteerForHelp) component;
        requestVolunteerForHelp.populateHelpHistoryTable();
        requestVolunteerForHelp.populateNeedHelpListTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastName1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField commentsTextField;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JFormattedTextField dobField;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel firstName1;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel gender1;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextField helpNameTxtField;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel manageEnt3;
    private javax.swing.JTextField serviceTypeTxtField;
    private javax.swing.JLabel submitRequest;
    private javax.swing.JLabel viewYourProfile;
    private javax.swing.JLabel viewYourProfile1;
    // End of variables declaration//GEN-END:variables
}
