/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.serviceSeeker;

import business.person.ServiceSeeker;
import business.person.Person;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author prasanna
 */
public class ViewVitalSignInfoJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount; 
    private Person person;
 
    
    /**
     * Creates new form UpdateVitalSignInfo
     */
    public ViewVitalSignInfoJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        person = userAccount.getPerson();
        
         ServiceSeeker customer = (ServiceSeeker)person;
        if(customer.isShareVitalInfo() && customer.isHasHealthIsuues())
        {
         for(String vs : customer.getVitalSignTrackingList())
         {
            vitalSignTrackList.append(vs + System.getProperty("line.separator"));
         }

          if(customer.isHasSensorDevice())
          {
              hasSensorRadioYes1.setSelected(true);
          }
          else
          {
           hasSensorRadioNo1.setSelected(true);
          }
            if(customer.isGetAlerts())
            {
            getAlertJRadioYes1.setSelected(true);
            }
            else
            {
              getAlertJRadioNo1.setSelected(true);
            }
   
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getAlert2 = new javax.swing.JLabel();
        getAlert3 = new javax.swing.JLabel();
        getAlertJRadioNo1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        hasSensorRadioNo1 = new javax.swing.JRadioButton();
        viewYourProfile3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vitalSignTrackList = new javax.swing.JTextArea();
        hasSensorRadioYes1 = new javax.swing.JRadioButton();
        getAlertJRadioYes1 = new javax.swing.JRadioButton();
        manageEnt1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(21, 25, 28));
        setForeground(new java.awt.Color(255, 255, 255));

        getAlert2.setForeground(new java.awt.Color(169, 224, 49));
        getAlert2.setText("Get alert from Senior Safe");

        getAlert3.setForeground(new java.awt.Color(169, 224, 49));
        getAlert3.setText("Vital Signs device to track Vital Signs");

        getAlertJRadioNo1.setBackground(new java.awt.Color(21, 25, 28));
        getAlertJRadioNo1.setText("No");
        getAlertJRadioNo1.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("Vital Signs you would like to track:");

        hasSensorRadioNo1.setBackground(new java.awt.Color(21, 25, 28));
        hasSensorRadioNo1.setText("No");
        hasSensorRadioNo1.setEnabled(false);

        viewYourProfile3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewYourProfile3.setForeground(new java.awt.Color(169, 224, 49));
        viewYourProfile3.setText("Vital Sign Information:");

        vitalSignTrackList.setEditable(false);
        vitalSignTrackList.setBackground(new java.awt.Color(31, 36, 42));
        vitalSignTrackList.setColumns(20);
        vitalSignTrackList.setRows(5);
        vitalSignTrackList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        vitalSignTrackList.setEnabled(false);
        jScrollPane1.setViewportView(vitalSignTrackList);

        hasSensorRadioYes1.setBackground(new java.awt.Color(21, 25, 28));
        hasSensorRadioYes1.setForeground(new java.awt.Color(169, 224, 49));
        hasSensorRadioYes1.setText("Yes");
        hasSensorRadioYes1.setEnabled(false);

        getAlertJRadioYes1.setBackground(new java.awt.Color(21, 25, 28));
        getAlertJRadioYes1.setText("Yes");
        getAlertJRadioYes1.setEnabled(false);

        manageEnt1.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt1.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt1.setText("Senior Safe");

        backJButton.setBackground(new java.awt.Color(152, 201, 45));
        backJButton.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(21, 25, 28));
        backJButton.setText("<<Back");
        backJButton.setBorder(null);
        backJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton.setFocusPainted(false);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewYourProfile3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(getAlertJRadioYes1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(getAlertJRadioNo1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hasSensorRadioYes1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hasSensorRadioNo1))
                                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(getAlert2)
                            .addComponent(getAlert3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(manageEnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(manageEnt1)
                .addGap(18, 18, 18)
                .addComponent(viewYourProfile3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(getAlert2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(getAlert3)
                            .addGap(38, 38, 38)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasSensorRadioYes1)
                            .addComponent(hasSensorRadioNo1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getAlertJRadioYes1)
                            .addComponent(getAlertJRadioNo1))))
                .addGap(42, 42, 42)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        layout.previous(userProcessContainer);    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel getAlert2;
    private javax.swing.JLabel getAlert3;
    private javax.swing.JRadioButton getAlertJRadioNo1;
    private javax.swing.JRadioButton getAlertJRadioYes1;
    private javax.swing.JRadioButton hasSensorRadioNo1;
    private javax.swing.JRadioButton hasSensorRadioYes1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel viewYourProfile3;
    private javax.swing.JTextArea vitalSignTrackList;
    // End of variables declaration//GEN-END:variables
}
