/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manager;

import business.EcoSystem;
import business.common.Validation;
import business.enterprises.Enterprise;
import business.organizations.DonorOrganization;
import business.organizations.ServiceSeekerOrganization;
import business.organizations.Organization;
import business.organizations.TransportOrganization;
import business.organizations.VolunteerOrganization;
import business.userAccount.UserAccount;
import business.workQueue.DonationRequest;
import business.workQueue.NeedServiceRequest;
import business.workQueue.NeedVitalSignDeviceRq;
import business.workQueue.SupervisorWorkRequest;
import business.workQueue.WorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map.Entry;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author daniel
 */
public class SeniorSafeEnterpriseManagerWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
   private  Enterprise enterprise;
   private EcoSystem ecoSystem;
   private UserAccount userAccount;
   private VolunteerOrganization vo;
    private DonorOrganization do1 ;
    private ServiceSeekerOrganization hsOrg;
    private TransportOrganization transOrg;
    private List<Entry<String, Integer>> topVolunteeerList;
     private List<Entry<String, Integer>> topDonorList;
    
    /**
     * Creates new form HeartHelpEnterpriseManagerWorkArea
     */
    public SeniorSafeEnterpriseManagerWorkArea(JPanel userProcessContainer, Enterprise enterprise, EcoSystem ecoSystem, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        valueLabel.setText(enterprise.getOrganizationName());
        populatePieChartData();
        populateTextFields();
        
        viewDetailedReportBtn.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        manageEnt1 = new javax.swing.JLabel();
        manageEnt2 = new javax.swing.JLabel();
        pieChartPanel = new javax.swing.JPanel();
        top3VolunteersBtn = new javax.swing.JButton();
        totalHelpReq = new javax.swing.JLabel();
        totSenDevReq = new javax.swing.JLabel();
        totTransReq = new javax.swing.JLabel();
        totSenDevReqField = new javax.swing.JTextField();
        totTransReqField = new javax.swing.JTextField();
        totHelpReqField = new javax.swing.JTextField();
        findTop3Donors = new javax.swing.JButton();
        viewDetailedReportBtn = new javax.swing.JButton();
        totSenDevReq1 = new javax.swing.JLabel();
        donatedAmntField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        valueLabel.setFont(new java.awt.Font("Malayalam MN", 0, 24)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(169, 224, 49));
        valueLabel.setText("<value>");

        manageEnt1.setFont(new java.awt.Font("Malayalam MN", 0, 24)); // NOI18N
        manageEnt1.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt1.setText("Senior Safe  Manager Work Area");

        manageEnt2.setFont(new java.awt.Font("Malayalam MN", 0, 24)); // NOI18N
        manageEnt2.setForeground(new java.awt.Color(169, 224, 49));
        manageEnt2.setText("Enterprise:");

        pieChartPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pieChartPanelLayout = new javax.swing.GroupLayout(pieChartPanel);
        pieChartPanel.setLayout(pieChartPanelLayout);
        pieChartPanelLayout.setHorizontalGroup(
            pieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        pieChartPanelLayout.setVerticalGroup(
            pieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        top3VolunteersBtn.setForeground(new java.awt.Color(169, 224, 49));
        top3VolunteersBtn.setText("View Top 3 Volunteers");
        top3VolunteersBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        top3VolunteersBtn.setContentAreaFilled(false);
        top3VolunteersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top3VolunteersBtnActionPerformed(evt);
            }
        });

        totalHelpReq.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        totalHelpReq.setForeground(new java.awt.Color(169, 224, 49));
        totalHelpReq.setText("Total No of Service Requests");

        totSenDevReq.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        totSenDevReq.setForeground(new java.awt.Color(169, 224, 49));
        totSenDevReq.setText("Total No of Sensor Device Requests");

        totTransReq.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        totTransReq.setForeground(new java.awt.Color(169, 224, 49));
        totTransReq.setText("Total No of Transport Requests");

        totSenDevReqField.setEditable(false);
        totSenDevReqField.setBackground(new java.awt.Color(0, 0, 0));
        totSenDevReqField.setForeground(new java.awt.Color(169, 224, 49));
        totSenDevReqField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totSenDevReqField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        totTransReqField.setEditable(false);
        totTransReqField.setBackground(new java.awt.Color(0, 0, 0));
        totTransReqField.setForeground(new java.awt.Color(169, 224, 49));
        totTransReqField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totTransReqField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        totHelpReqField.setEditable(false);
        totHelpReqField.setBackground(new java.awt.Color(0, 0, 0));
        totHelpReqField.setForeground(new java.awt.Color(169, 224, 49));
        totHelpReqField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totHelpReqField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        findTop3Donors.setForeground(new java.awt.Color(169, 224, 49));
        findTop3Donors.setText("View Top 3 Donors");
        findTop3Donors.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        findTop3Donors.setContentAreaFilled(false);
        findTop3Donors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTop3DonorsActionPerformed(evt);
            }
        });

        viewDetailedReportBtn.setForeground(new java.awt.Color(169, 224, 49));
        viewDetailedReportBtn.setText("View Detailed Report");
        viewDetailedReportBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        viewDetailedReportBtn.setContentAreaFilled(false);
        viewDetailedReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailedReportBtnActionPerformed(evt);
            }
        });

        totSenDevReq1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        totSenDevReq1.setForeground(new java.awt.Color(169, 224, 49));
        totSenDevReq1.setText("Total Amount Donated By Donors");

        donatedAmntField.setEditable(false);
        donatedAmntField.setBackground(new java.awt.Color(0, 0, 0));
        donatedAmntField.setForeground(new java.awt.Color(169, 224, 49));
        donatedAmntField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        donatedAmntField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(manageEnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totSenDevReq1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalHelpReq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(manageEnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(totSenDevReq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totTransReq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totSenDevReqField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totTransReqField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totHelpReqField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(donatedAmntField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(viewDetailedReportBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(findTop3Donors, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(top3VolunteersBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(pieChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pieChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageEnt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valueLabel)
                            .addComponent(manageEnt2))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalHelpReq)
                            .addComponent(totHelpReqField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totTransReq)
                            .addComponent(totTransReqField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totSenDevReq)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totSenDevReqField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totSenDevReq1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(donatedAmntField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(40, 40, 40)
                        .addComponent(top3VolunteersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findTop3Donors, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewDetailedReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void top3VolunteersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top3VolunteersBtnActionPerformed
       findTop3Volunteers();
       if(topVolunteeerList!=null && topDonorList!=null && !(topVolunteeerList.isEmpty()) && !(topDonorList.isEmpty()) )
       {
       viewDetailedReportBtn.setVisible(true);
       }
    }//GEN-LAST:event_top3VolunteersBtnActionPerformed

    private void findTop3DonorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTop3DonorsActionPerformed
        findTop3Donors();
       if(topVolunteeerList!=null && topDonorList!=null && !(topVolunteeerList.isEmpty()) && !(topDonorList.isEmpty()) )
       {
       viewDetailedReportBtn.setVisible(true);
       }
    }//GEN-LAST:event_findTop3DonorsActionPerformed

    private void viewDetailedReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailedReportBtnActionPerformed
       if(topVolunteeerList == null || topDonorList == null || topVolunteeerList.isEmpty() && topDonorList.isEmpty())
       {
        JOptionPane.showMessageDialog(null, " No Data to display as of now!","warning", JOptionPane.WARNING_MESSAGE);
        return;     
       }
        ViewDetailedReportJPanel vdrjp = new ViewDetailedReportJPanel(userProcessContainer, topVolunteeerList, topDonorList);
        userProcessContainer.add("ViewDetailedReportJPanel", vdrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDetailedReportBtnActionPerformed
    
      public void populateTextFields()
      {
          int totalHelpReq = 0;
          int totalTransportReq = 0;
          String totalDonorReq = "";
          int totalAmountDonated =0;
          try
          {
      if(do1!=null){
      totalDonorReq = String.valueOf(do1.getWorkQueue().getWorkRequestList().size());
              
        for(UserAccount donorAccount : do1.getUserAccountDirectory().getUserAccountDirectory())
      {
       if(!donorAccount.getWorkQueue().getWorkRequestList().isEmpty())
       {
         for(WorkRequest wrkrequest : donorAccount.getWorkQueue().getWorkRequestList())
         {  
           if(wrkrequest.getMessage().equalsIgnoreCase("Donated Money"))
             {
                 DonationRequest donationRequest = (DonationRequest)wrkrequest;
                totalAmountDonated+= Integer.parseInt(donationRequest.getDonationAmount().getDonationAmount());
             }
        
          }
         }
         
       }
         } 
      if(vo!=null)
      {
          for(WorkRequest request : vo.getWorkQueue().getWorkRequestList())
          {
             if(request.getMessage().equalsIgnoreCase("Need Service"))
             {
               totalHelpReq++;     
             }
             
             
           }
          for(UserAccount userAccount : vo.getUserAccountDirectory().getUserAccountDirectory())
          {
           if(!userAccount.getWorkQueue().getWorkRequestList().isEmpty())
           {
            for(WorkRequest req : userAccount.getWorkQueue().getWorkRequestList())
            {
              if(req.getMessage().equalsIgnoreCase("Need Service"))
             {
               totalHelpReq++;     
             }   
            }
           }
          }
      } 
      if(transOrg!=null)
      {
           for(WorkRequest request : transOrg.getWorkQueue().getWorkRequestList())
          {
              if(request.getMessage().equals("Need Transport"))
              {
              totalTransportReq++;    
              }
          }
      }   
          totHelpReqField.setText(String.valueOf(totalHelpReq));
          totSenDevReqField.setText(totalDonorReq);
          totTransReqField.setText(String.valueOf(totalTransportReq));
          donatedAmntField.setText(String.valueOf(totalAmountDonated));
          }
          catch(Exception e)
          {
         JOptionPane.showMessageDialog(null, " Data is not availble for few organizations!","warning", JOptionPane.WARNING_MESSAGE);
         return;      
          }
      }
    
    public void populatePieChartData()
    {
       DefaultPieDataset dataSet = new DefaultPieDataset();
       int totalHelpSeekers = 0;
       int totalVolunteers = 0;
       int totalDonors = 0;
       int totalDrivers = 0;
       try
       {
       for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationDirectory())
       {
          if(organization instanceof ServiceSeekerOrganization)
          {
          this.hsOrg = (ServiceSeekerOrganization)organization;
           totalHelpSeekers = organization.getPersonDirectory().getCustomerDirectory().size();
          }
       }
       try
       {
         this.vo = Validation.getVO(ecoSystem, userAccount);
       }
        catch(NullPointerException npe)
       {
        JOptionPane.showMessageDialog(null, " Voluteer Organination does not exist!","warning", JOptionPane.WARNING_MESSAGE);
        return; 
       }
       if(vo!=null)
       {
        totalVolunteers = vo.getPersonDirectory().getVolunteerDirectory().size();
       }
        
        this.do1 = Validation.getDonorOrganization(ecoSystem, userAccount);
        if(do1!=null)
        {
        totalDonors = do1.getPersonDirectory().getPersonDirectory().size();
        }
        this.transOrg = Validation.getTO(ecoSystem, userAccount);
        if(transOrg!=null)
        {
        totalDrivers = transOrg.getPersonDirectory().getPersonDirectory().size();
        }
         
         dataSet.setValue("Total No of Service Seekers",totalHelpSeekers);
         dataSet.setValue("Total No of Volunteers", totalVolunteers );
         dataSet.setValue("Total No of Donors",totalDonors);
         dataSet.setValue("Total No of Drivers",totalDrivers);
     
         JFreeChart  chart = ChartFactory.createPieChart3D("Pie Chart for "+userAccount.getNetwork().getCity(), dataSet, true, true, Locale.ENGLISH);
            chart.setBackgroundPaint(Color.WHITE);
            chart.getTitle().setPaint(Color.BLUE);
          ChartPanel chartpanel = new ChartPanel(chart);
        chartpanel.setDomainZoomable(true);

        pieChartPanel.setLayout(new BorderLayout());
        pieChartPanel.add(chartpanel, BorderLayout.EAST); 
        pieChartPanel.setVisible(true);
       }
       
       catch(NullPointerException npe)
       {
        JOptionPane.showMessageDialog(null, " No Data to display as of now!","warning", JOptionPane.WARNING_MESSAGE);
        return; 
       }
        
    }
    
    public void findTop3Volunteers()
    {
     int noOfRequests = 0;  
     HashMap<String, Integer> volMap = new HashMap<>(); 
      try
      {
     for(UserAccount volunteerAccount : vo.getUserAccountDirectory().getUserAccountDirectory())
      {
        if(!volunteerAccount.getWorkQueue().getWorkRequestList().isEmpty())
       {
         for(WorkRequest request : volunteerAccount.getWorkQueue().getWorkRequestList() )
         {
          if(request.getMessage().equalsIgnoreCase("Need Service") && 
                  request.getStatus().equalsIgnoreCase("Completed") )
          {
              NeedServiceRequest nhwr = (NeedServiceRequest)request;  
          if(nhwr.getRequestResult().equalsIgnoreCase(SupervisorWorkRequest.REQUEST_ACCEPT))
          {
          ++noOfRequests;    
          }
          }
         }
          volMap.put(volunteerAccount.getPerson().getFullName(), noOfRequests);
          noOfRequests = 0;
         }
        
       }
     
          System.out.println("volMap >>>>>>" +volMap.toString());
            
          List<Entry<String, Integer>> list = new LinkedList<>(volMap.entrySet());
        
          Collections.sort(list, new Comparator<Entry<String, Integer>>()
            {
            public int compare(Entry<String, Integer> o1,
                    Entry<String, Integer> o2)
            {
               if(o1.getValue()>o2.getValue())
               {
                return 1;
               }
                else if(o1.getValue()<o2.getValue())
                {
                    return -1;
                }
                return 0;
            }
             
            });
          Collections.reverse(list);
          System.out.println("After Sort "+list.toString());
          
          topVolunteeerList = list;
          
          DefaultCategoryDataset  dataSet = new DefaultCategoryDataset();
          int count = 0;
        
            if(volMap.entrySet().size()<=3)
            {
           for (Entry<String, Integer> entry : list)
            {
            System.out.println("Key : " + entry.getKey() + " Value : "+ entry.getValue());
            dataSet.setValue(entry.getValue(), "No of Service Requests", entry.getKey());
            }
            }
            else  if(volMap.entrySet().size()>3)
            {
            for (Entry<String, Integer> entry : list)
            {
            System.out.println("Key : " + entry.getKey() + " Value : "+ entry.getValue());
            dataSet.setValue(entry.getValue(), "No of Service Requests", entry.getKey());
            count ++;
            if(count == 3)
            {
              break;
            }
            }
            }
             JFreeChart barchart = ChartFactory.createBarChart(" Top 3 Volunteers by no of Requests " ," Volunteer Name " ,"No of Help Requests", dataSet,PlotOrientation.VERTICAL, false, true, false);
             barchart.setBackgroundPaint(Color.WHITE);
             barchart.getTitle().setPaint(Color.BLUE);
             CategoryPlot plot = barchart.getCategoryPlot();
             plot.setBackgroundPaint(Color.CYAN);
             
            ChartFrame frame = new ChartFrame("Bar Chart for Top 3 Volunteers ", barchart);
            frame.setVisible(true);
            frame.setSize(450,350);
            
      }
      catch(NullPointerException npe)
       {
        npe.printStackTrace();
        JOptionPane.showMessageDialog(null, " No Data to display as of now!","warning", JOptionPane.WARNING_MESSAGE);
        return; 
       
       }
      
    }
    
     public void findTop3Donors()
    {
        
     int noOfRequests = 0;  
     int donatedAmount = 0;
     HashMap<String, Integer> donorMap = new HashMap<>(); 
     HashMap<String, Integer> donorAmountMap = new HashMap<>();
      try
      {
     if(do1 ==null)
     {
     JOptionPane.showMessageDialog(null, "Donor Organization does not exist!","warning", JOptionPane.WARNING_MESSAGE);
        return;    
     }
     for(UserAccount donorAccount : do1.getUserAccountDirectory().getUserAccountDirectory())
      {
             System.out.println("request"+donorAccount.getuName());
        if(!donorAccount.getWorkQueue().getWorkRequestList().isEmpty())
       {
           System.out.println("request"+donorAccount.getuName());
        for(WorkRequest wrkrequest : donorAccount.getWorkQueue().getWorkRequestList() )
         {  
           if(wrkrequest.getMessage().equalsIgnoreCase("Donated Money"))
             {
                 DonationRequest donationRequest = (DonationRequest)wrkrequest;
                donatedAmount+= Integer.parseInt(donationRequest.getDonationAmount().getDonationAmount());
               ++noOfRequests; 
             }
           if(wrkrequest.getMessage().equalsIgnoreCase("Need Sensor Device"))
           {
               NeedVitalSignDeviceRq nsdwr = (NeedVitalSignDeviceRq)wrkrequest;
               if(nsdwr.getdonationRequestResult().equalsIgnoreCase(SupervisorWorkRequest.REQUEST_ACCEPT))
               {
               ++noOfRequests; 
               }
           }
          }
          noOfRequests+=donatedAmount;  
         donorMap.put(donorAccount.getPerson().getFullName(), noOfRequests);
         noOfRequests=0;
        }
         
       }

         List<Entry<String, Integer>> list = new LinkedList<>(donorMap.entrySet());
        
          Collections.sort(list, new Comparator<Entry<String, Integer>>()
            {
            public int compare(Entry<String, Integer> o1,
                    Entry<String, Integer> o2)
            {
               return o1.getValue().compareTo(o2.getValue());
             }
            });
          Collections.reverse(list);
          
          topDonorList = list;
          
          DefaultCategoryDataset  dataSet = new DefaultCategoryDataset();
          int count = 0;
        
            if(donorMap.entrySet().size()<=3)
            {
           for (Entry<String, Integer> entry : list)
            {
            System.out.println("Key : " + entry.getKey() + " Value : "+ entry.getValue());
            dataSet.setValue(entry.getValue(), "Values", entry.getKey());
            }
            }
            else  if(donorMap.entrySet().size()>3)
            {
            for (Entry<String, Integer> entry : list)
            {
            System.out.println("Key : " + entry.getKey() + " Value : "+ entry.getValue());
            dataSet.setValue(entry.getValue(), "Values", entry.getKey());
            count ++;
            if(count == 3)
            {
                break;
            }
            }
            }
             JFreeChart barchart = ChartFactory.createBarChart(" Top 3 Donors " ," Donor Name " ,"No of Requests", dataSet,PlotOrientation.VERTICAL, false, true, false);
             barchart.setBackgroundPaint(Color.WHITE);
             barchart.getTitle().setPaint(Color.BLUE);
             CategoryPlot plot = barchart.getCategoryPlot();
             plot.setBackgroundPaint(Color.CYAN);
            ChartFrame frame = new ChartFrame("Bar Chart for Top 3 Donors ", barchart);
            frame.setVisible(true);
            frame.setSize(450,350);
         
      }
      catch(NullPointerException npe)
       {
        JOptionPane.showMessageDialog(null, " No Data to display as of now!","warning", JOptionPane.WARNING_MESSAGE);
        return; 
       }
      
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField donatedAmntField;
    private javax.swing.JButton findTop3Donors;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel manageEnt2;
    private javax.swing.JPanel pieChartPanel;
    private javax.swing.JButton top3VolunteersBtn;
    private javax.swing.JTextField totHelpReqField;
    private javax.swing.JLabel totSenDevReq;
    private javax.swing.JLabel totSenDevReq1;
    private javax.swing.JTextField totSenDevReqField;
    private javax.swing.JLabel totTransReq;
    private javax.swing.JTextField totTransReqField;
    private javax.swing.JLabel totalHelpReq;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewDetailedReportBtn;
    // End of variables declaration//GEN-END:variables
}
